
# Train on augmented data; validate and test on non-augmented scenario-batch loader

train:
  epochs: 200
  batch_size: 16
  lr: 1.0e-3
  encoder_backbone_lr_mult: 1.0
  itr_per_epoch: 1.0e+8
  dataloader: augmented
  augmentation_mode: "pad_and_resize"
  resize_options:
    - [768, 768]

valid:
  batch_size: 16
  dataloader: augmented
  augmentation_mode: "pad_and_resize"
  resize_options:
    - [768, 768]

test:
  batch_size: 16
  dataloader: augmented
  augmentation_mode: "pad_and_resize"
  resize_options:
    - [768, 768]
  return_scen_map: true  # set true to compute collision metrics

diffusion:
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  scenmapemb: 256
  target_strategy: "random"
  map_encoder:
    grid_size: 7
    finetune_from: "layer4"

dataset:
  scenarios: null
